version: "3.4"
services:
  server:
    build: .
    restart: always
    network_mode: host
    env_file: .env
    environment:
      PORT: "3004"
    command: python forecaster/server.py
  scrapper:
    build: .
    restart: always
    network_mode: host
    env_file: .env
